### ISSUE TITLE
Tweaks to `predict` method of `ModelBuilder`

### ISSUE THREAD

**Issue by drbenvincent** [pymc-devs/pymcx#88]
Remove `point_estimate` kwarg of the `ModelBuilder.predict` method. Instead have two distinct methods... 
* `predict` (which returns the full idata) and 
* `predict_point` which returns the point estimate.

Tagging @michaelosthege, @twiecki.

**Comment by twiecki** [comment]
CC @shashank

**Comment by drbenvincent** [comment]
Maybe even an additional `predict_proba` to fit in with sktime API https://www.sktime.org/en/stable/examples/01_forecasting.html?highlight=predict_proba#predict_proba---distribution-predictions

**Comment by twiecki** [comment]
@drbenvincent yeah, I think that's a good idea.
